# any config that is shared within all configurations 
version: "3"
services:
    node-app:
        build: . #path to dockerfile 
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
        # this would be for env file
        # env_file: 
        #     - ./.env

    mongo-database:
        # do not need build here becuase we just want to use the image without any modifications
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin