# any config that is shared within all configurations 
version: "3"
services:
    node-app:
        build: . #path to dockerfile 
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
        # this would be for env file
        # env_file: 
        #     - ./.env
